name: Build, Test and Validate Package

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - '.github/workflows/**'
      - 'setup.py'
      - 'pyproject.toml'
      - 'requirements.txt'

jobs:
  test:
    permissions:
      contents: write
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest

    - name: Install build tools
      run: |
        pip install build

    - name: Build package
      run: |
        python -m build
        # Debug: List contents of dist directory
        Write-Host "Contents of dist directory:"
        Get-ChildItem dist/ -Recurse

    - name: Test package installation
      run: |
        # Debug: Check if dist directory exists and list contents
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Dist directory exists: $(Test-Path dist)"
        if (Test-Path dist) {
          Write-Host "Contents of dist directory:"
          Get-ChildItem dist/ -Recurse
        }

        # Create virtual environment
        python -m venv test_env
        .\test_env\Scripts\activate

        # Install the wheel file (use specific filename)
        $wheelFile = Get-ChildItem dist/*.whl | Select-Object -First 1
        if ($wheelFile) {
          Write-Host "Installing wheel: $($wheelFile.FullName)"
          pip install $wheelFile.FullName

          # Test CLI entry point
          Write-Host "Testing CLI entry point..."
          try {
            instagram-updates --help
          } catch {
            Write-Host "Direct CLI failed, trying module approach..."
            python -m instagram_updates.cli --help
          }

          # Test module imports
          Write-Host "Testing module imports..."
          python -c "import instagram_scraper; import report_generator; import browser_manager; print('All modules imported successfully')"
        } else {
          Write-Host "No wheel file found in dist directory!"
          exit 1
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: dist/
        retention-days: 30