name: Build, Test and Validate Package

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - '.github/workflows/**'
      - 'setup.py'
      - 'pyproject.toml'
      - 'requirements.txt'

jobs:
  test:
    permissions:
      contents: write
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest

    - name: Install build tools
      run: |
        pip install build

    - name: Build package
      run: |
        python -m build

    - name: Test package installation
      run: |
        python -m venv test_env
        .\test_env\Scripts\activate
        pip install dist/*.whl
        # Test the CLI entry point (try both ways)
        instagram-updates --help || python -m instagram_updates.cli --help
        # Test that modules can be imported
        python -c "import instagram_scraper; import report_generator; import browser_manager; print('All modules imported successfully')"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: dist/
        retention-days: 30