name: Release Pipeline

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/**"
      - "pyproject.toml"
      - "templates/**"
  pull_request:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/**"
      - "pyproject.toml"
      - "templates/**"

env:
  BROWSER_PATH: "/usr/bin/chromium-browser"
  BROWSER_USER_DATA_DIR: "/tmp/browser-data"
  BROWSER_PROFILE_DIR: "Default"
  BROWSER_DEBUG_PORT: "9222"
  BROWSER_START_URL: "https://www.instagram.com/"
  BROWSER_LOAD_DELAY: "5000"
  BROWSER_CONNECT_SCHEME: "http"
  BROWSER_REMOTE_HOST: "localhost"
  OUTPUT_DIR: "/tmp/output"
  LOG_DIR: "/tmp/logs"
  TEMPLATE_PATH: "templates/template.html"
  TIMEZONE_OFFSET: "2"
  INSTAGRAM_URL: "https://www.instagram.com/"
  INSTAGRAM_MAX_POSTS_PER_ACCOUNT: "5"
  INSTAGRAM_POST_LOAD_TIMEOUT: "10000"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          playwright install --with-deps
      - run: |
          ruff check . --fix
          mypy .
          pytest tests/ -v --cov=. --cov-report=xml --cov-report=term-missing
      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  release:
    needs: test
    runs-on: windows-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install -e . pyinstaller
      - run: |
          python -m pytest
      - run: |
          pyinstaller --onefile --windowed run.py --name instagram-helper
          Compress-Archive -Path dist\instagram-helper.exe -DestinationPath dist\instagram-helper.zip
      - name: Set Version
        id: version
        run: |
          $version = "v$(Get-Date -Format 'yyyy.MM.dd')"
          echo "version=$version" >> $env:GITHUB_OUTPUT
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin ${{ steps.version.outputs.version }}
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            Automated release from commit #${{ github.event.head_commit.id }}
            ${{ github.event.head_commit.message }}
          files: dist/instagram-helper.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
