name: Release Pipeline

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - ".github/workflows/**"
      - "pyproject.toml"
      - "templates/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build-release:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]" pyinstaller
          playwright install

      - name: Lint and Type-Check
        run: |
          ruff check . --fix
          mypy .

      - name: Tests with Coverage
        run: |
          python -m pytest tests/ -v --cov=. --cov-report=xml --cov-report=term-missing

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false

      - name: Build Artifact
        run: |
          pyinstaller --onefile --windowed run.py --name instagram-helper
          Compress-Archive -Path dist\instagram-helper.exe -DestinationPath dist\instagram-helper.zip

      - name: Determine Version
        id: ver
        run: |
          $v = "v$(Get-Date -Format 'yyyy.MM.dd')-${{ github.run_number }}"
          echo "version=$v" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.ver.outputs.version }}
          name: Release ${{ steps.ver.outputs.version }}
          body: |
            Automated release from ${{ github.sha }}
            ${{ github.event.head_commit.message }}
          files: dist/instagram-helper.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
